### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by AmauryG13** [MacSup/Sentence-Generator#1]
https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by CamilleMoriot** [comment]
on it

**Comment by AmauryG13** [comment]
Il faut créer un [nofication](https://laravel.com/docs/8.x/notifications#introduction) de Laravel au même de l'ajout d'une nouvelle Sentence.

Tu peux faire direct dans la branche dev

**Comment by AmauryG13** [comment]
@CamilleMoriot j'ai légèrement modifié ce que tu avais fait (juste réduit la taille un peu)
Est ce que tu pourrais faire la même chose pour la page generator ?

l'HTML se situe dans le fichier [resources/js/components/Generator.vue](https://github.com/MacSup/Sentence-Generator/blob/feature/frontend/resources/js/components/Generator.vue)
